export default {
	HTTP_OK:                    200,

	HTTP_BAD_REQUEST:           400,
	HTTP_UNAUTHORIZED:          401,
	HTTP_FORBIDDEN:             403,
	HTTP_NOT_FOUND:             404,
	HTTP_REQUEST_TIMEOUT:       408,
	HTTP_CONFLICT:              409,
	HTTP_VALIDATION_FAILURE:    422,
	HTTP_TOO_MANY_REQUESTS:     429,

	HTTP_INTERNAL_SERVER_ERROR: 500,
	HTTP_SERVICE_UNAVAILABLE:   503,

	ONE_WEEK_MILLISECONDS:      6.048e+8,
	TWO_HOURS_MILLISECONDS:     7.2e+6
} as const;