export default {
	AUTH_ACCESS_TOKEN_KEY:      "CB_ACCESS_TOKEN",
	AUTH_REFRESH_TOKEN_KEY:     "CB_REFRESH_TOKEN",
	AUTH_ACCESS_TOKEN_EXPIRED:  "2 hours",
	AUTH_REFRESH_TOKEN_EXPIRED: "7 days"
} as const;